/* eslint-disable react/jsx-props-no-spreading */
import * as React from 'react';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import '../styles/globals.css';
import Header from './_header';

const MyApp = ({ Component, pageProps }: AppProps) => (
  <>
    <style jsx>{`
      main div {
        margin: 2vh 5vw;
        max-width: 860px;
      }

      @media (min-width: 860px) {
        main {
          display: flex;
          flex-direction: column;
          align-items: center;
        }

        main div {
          margin: 2vh 0;
          width: 860px;
        }
      }
    `}</style>
    <Head>
      <title>Andrew Dibble codes</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.png" />
      <script src="https://kit.fontawesome.com/15f0bb2341.js" crossOrigin="anonymous" async />
    </Head>
    <Header />
    <main>
      <div>
        <Component {...pageProps} />
      </div>
    </main>
  </>
);
export default MyApp;
